# Generated by Django 5.1.3 on 2024-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagenLibro',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='libro',
            field=models.CharField(choices=[('ciencia_ficción', 'Ciencia_Ficción'), ('novelas', 'Novelas'), ('autoayuda', 'Autoayuda'), ('terror', 'Terror'), ('otro', 'Otro')], default='autoayuda', max_length=15),
        ),
    ]
